spring.application.name=Desk2Dine

app.datasource.url=jdbc:mysql://localhost:3306/desk2dine?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
app.datasource.username=root
app.datasource.password=442006c
app.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
app.datasource.pool-size=10

app.base-url=http://localhost:8082

server.port=8082

server.servlet.session.cookie.http-only=true
server.servlet.session.timeout=30m
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false

server.error.include-message=never
server.error.include-stacktrace=never